version: '3'

services:
  iqdnode0:
    container_name: iqdnode0
    image: "bitwebs/iqd-env"
    ports:
      - "9090:9090"
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-iqd.log}
    volumes:
      - ./build:/iqd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  iqdnode1:
    container_name: iqdnode1
    image: "bitwebs/iqd-env"
    ports:
      - "9091:9090"
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-iqd.log}
    volumes:
      - ./build:/iqd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  iqdnode2:
    container_name: iqdnode2
    image: "bitwebs/iqd-env"
    environment:
      - ID=2
      - LOG=$${LOG:-iqd.log}
    ports:
      - "9092:9090"
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/iqd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  iqdnode3:
    container_name: iqdnode3
    image: "bitwebs/iqd-env"
    environment:
      - ID=3
      - LOG=$${LOG:-iqd.log}
    ports:
      - "9093:9090"
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/iqd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
