// Package types nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/bitwebs/iq-core/types/assets/
// ALIASGEN: github.com/bitwebs/iq-core/types/util/
package types

import (
	"github.com/bitwebs/iq-core/types/assets"
	"github.com/bitwebs/iq-core/types/util"
)

const (
	MicroBiqDenom       = assets.MicroBiqDenom
	MicroBUSDDenom        = assets.MicroBUSDDenom
	MicroBKRWDenom        = assets.MicroBKRWDenom
	MicroBSDRDenom        = assets.MicroBSDRDenom
	MicroBCNYDenom        = assets.MicroBCNYDenom
	MicroBJPYDenom        = assets.MicroBJPYDenom
	MicroBEURDenom        = assets.MicroBEURDenom
	MicroBGBPDenom        = assets.MicroBGBPDenom
	MicroBMNTDenom        = assets.MicroBMNTDenom
	MicroUnit            = assets.MicroUnit
	BlocksPerMinute      = util.BlocksPerMinute
	BlocksPerHour        = util.BlocksPerHour
	BlocksPerDay         = util.BlocksPerDay
	BlocksPerWeek        = util.BlocksPerWeek
	BlocksPerMonth       = util.BlocksPerMonth
	BlocksPerYear        = util.BlocksPerYear
	CoinType             = util.CoinType
	FullFundraiserPath   = util.FullFundraiserPath
	Bech32PrefixAccAddr  = util.Bech32PrefixAccAddr
	Bech32PrefixAccPub   = util.Bech32PrefixAccPub
	Bech32PrefixValAddr  = util.Bech32PrefixValAddr
	Bech32PrefixValPub   = util.Bech32PrefixValPub
	Bech32PrefixConsAddr = util.Bech32PrefixConsAddr
	Bech32PrefixConsPub  = util.Bech32PrefixConsPub
	SwartzChainID      = "swartz-1"
	McAfeeChainID        = "mcafee-1"
)

// functions aliases
var (
	IsPeriodLastBlock = util.IsPeriodLastBlock
	AddressVerifier   = util.AddressVerifier
)
